### ISSUE TITLE
about 'expanded setting'

### ISSUE THREAD

**Issue by Crabbit-F** [ictnlp/CRESS#5]
Would you mind tell me detail about 'expanded setting' in papers.Is it mean use additional mt dataset on training but not only must?Thanks!

**Comment by Poeroz** [comment]
Thanks for your interests in our work! Yes, 'expanded setting' means using additional MT data in the MT training stage. The details about additional MT datasets can be found in Appendix A.

**Comment by Crabbit-F** [comment]
Thanks a lot! I had seen the WMT dataset on task en-es. And I can only get base setting score(31.9 on en-es) by following training order which on 'train.en-x.postln.wmt_pretrain.mustc_mt_pretrain.mustc_st+mt.cress.sh' ?

**Comment by Poeroz** [comment]
Did you pretrain the model with only wmt data or wmt+mustc data? In our experiments, we first pretrain on WMT data, and then pretrain on MuST-C MT data, and finally finetune on MuST-C ST data. What if you directly finetune the model with our released pretrained MT model?

**Comment by Crabbit-F** [comment]
I did't pretrain MT additional. Just use your released pretrained MT model.

**Comment by Poeroz** [comment]
Maybe it is because the "train.en-x.postln.wmt_pretrain.mustc_mt_pretrain.mustc_st+mt.cress.sh" script only train the model up to 20 epochs. If you want to use token-level adaptive training, you can continue train the model with "train.en-x.postln.wmt_pretrain.mustc_mt_pretrain.mustc_st+mt.cress_adaptive.sh" script. If not, you can remove `--max-epoch 20` in the script and continue train the model with some epochs.

**Comment by Crabbit-F** [comment]
So should I get 33.2 score but not 31.9 on en-es with your released pretrained MT model?

**Comment by Poeroz** [comment]
Yes. You should obtain results similar to those in our paper.

**Comment by Crabbit-F** [comment]
emmmmm. I found I did't use MT model but only hubert.
